# Ore populator percentages
ore:
  DESERT:
    COAL_ORE:
      tries: 15
      chanceOfSpawning: 60
      minY: 20
      maxY: 40
      chanceOfVein: 40
    IRON_ORE:
      tries: 10
      chanceOfSpawning: 30
      minY: 20
      maxY: 40
      chanceOfVein: 40
  FOREST:
    COAL_ORE:
      tries: 15
      chanceOfSpawning: 60
      minY: 20
      maxY: 40
      chanceOfVein: 40
    IRON_ORE:
      tries: 10
      chanceOfSpawning: 30
      minY: 20
      maxY: 40
      chanceOfVein: 40
  PLAINS:
    COAL_ORE:
      tries: 15
      chanceOfSpawning: 60
      minY: 20
      maxY: 40
      chanceOfVein: 40
    IRON_ORE:
      tries: 10
      chanceOfSpawning: 30
      minY: 20
      maxY: 40
      chanceOfVein: 40
  SWAMP:
    COAL_ORE:
      tries: 15
      chanceOfSpawning: 60
      minY: 20
      maxY: 40
      chanceOfVein: 40
    IRON_ORE:
      tries: 10
      chanceOfSpawning: 30
      minY: 20
      maxY: 40
      chanceOfVein: 40
  HILLS:
    COAL_ORE:
      tries: 15
      chanceOfSpawning: 60
      minY: 20
      maxY: 40
      chanceOfVein: 40
    IRON_ORE:
      tries: 10
      chanceOfSpawning: 30
      minY: 20
      maxY: 40
      chanceOfVein: 40


# Grass population
# Specify the percentage of each spawn material in the biome.
grass:
  DESERT:
    CACTUS:
      tries: 5
      data: 1
      percentage: 60
  PLAINS:
    LONG_GRASS:
      tries: 20
      data: 1
      percentage: 60
    RED_ROSE:
      tries: 3
      data: 0
      percentage: 40
    YELLOW_FLOWER:
      tries: 3
      data: 0
      percentage: 40
  FOREST:
    LONG_GRASS:
      tries: 20
      data: 1
      percentage: 60
    RED_ROSE:
      tries: 3
      data: 0
      percentage: 40
    YELLOW_FLOWER:
      tries: 3
      data: 0
      percentage: 40

trees:
  FOREST:
    TREE:
      tries: 3
      percentage: 60
  PLAINS:
    TREE:
      tries: 3
      percentage: 60
  SWAMP:
    SWAMP:
      tries: 3
      percentage: 60



# Determine the probability an item drop depending on richness.
# To add an entry just type:
# MATERIAL:SUBID:PROBABILITY;
# and simply delete the entry or set the probability to 0 or
# remove the item.
#
# If you want to add an enchantment to the item type:
# MATERIAL:SUBID:PROBABILITY:ENCHANTMENT:LEVEL;
#
# If you want to add a potion to the item type:
# MATERIAL:SUBID:PROBABILITY:POTION:DURATION:LEVEL:RGB;
#
# The MATERIAL needs to be the exact spigot 1.12 MATERIAL name: https://aboodyy.net/spigot-api/javadocs/1.12.2/org/bukkit/Material.html
# The ENCHANTMENT needs to be the exact spigot 1.12 ENCHANTMENT name: https://aboodyy.net/spigot-api/javadocs/1.12.2/org/bukkit/enchantments/Enchantment.html
# The POTION needs to be the exact spigot 1.12 POTION name: https://aboodyy.net/spigot-api/javadocs/1.12.2/org/bukkit/potion/PotionType.html
item-drops:
  0: 'COBBLESTONE:0:1:50;TORCH:0:10:20;DIRT:0:1:10;STONE:0:1:10;OBSIDIAN:0:1:10'
  1: 'GOLD_CHESTPLATE:0:1:2;GOLD_LEGGINGS:0:1:2;GOLD_HELMET:0:1:2;GOLD_BOOTS:0:1:2;IRON_CHESTPLATE:0:1:5;IRON_LEGGINGS:0:1:5;IRON_HELMET:0:1:5;IRON_BOOTS:0:1:5;DIAMOND_CHESTPLATE:0:1:1;DIAMOND_LEGGINGS:0:1:1;DIAMOND_HELMET:0:1:0.5;DIAMOND_BOOTS:0:1:0.5;GOLD_CHESTPLATE:0:1:3:PROTECTION_ENVIRONMENTAL:1;GOLD_LEGGINGS:0:1:1:PROTECTION_ENVIRONMENTAL:1;GOLD_HELMET:0:1:1:PROTECTION_ENVIRONMENTAL:1;GOLD_BOOTS:0:1:0.25:PROTECTION_ENVIRONMENTAL:1;IRON_CHESTPLATE:0:1:2:PROTECTION_ENVIRONMENTAL:1;IRON_LEGGINGS:0:1:2:PROTECTION_ENVIRONMENTAL:1;IRON_HELMET:0:1:2:PROTECTION_ENVIRONMENTAL:1;IRON_BOOTS:0:1:0.5:PROTECTION_ENVIRONMENTAL:1;DIAMOND_CHESTPLATE:0:1:1:PROTECTION_ENVIRONMENTAL:1;DIAMOND_LEGGINGS:0:1:3:PROTECTION_ENVIRONMENTAL:1;DIAMOND_HELMET:0:1:1:PROTECTION_ENVIRONMENTAL:1;DIAMOND_BOOTS:0:1:0.25:PROTECTION_ENVIRONMENTAL:1;IRON_CHESTPLATE:0:1:2:PROTECTION_ENVIRONMENTAL:2;IRON_LEGGINGS:0:1:2:PROTECTION_ENVIRONMENTAL:2;IRON_HELMET:0:1:4:PROTECTION_ENVIRONMENTAL:2;IRON_BOOTS:0:1:0.5:PROTECTION_ENVIRONMENTAL:2;DIAMOND_CHESTPLATE:0:1:1:PROTECTION_ENVIRONMENTAL:2;DIAMOND_LEGGINGS:0:1:1:PROTECTION_ENVIRONMENTAL:2;DIAMOND_HELMET:0:1:1:PROTECTION_ENVIRONMENTAL:2;DIAMOND_BOOTS:0:1:0.25:PROTECTION_ENVIRONMENTAL:2;GOLD_CHESTPLATE:0:1:0.5:PROTECTION_FIRE:1;GOLD_LEGGINGS:0:1:0.5:PROTECTION_FIRE:1;GOLD_HELMET:0:1:0.5:PROTECTION_FIRE:1;IRON_CHESTPLATE:0:1:3:PROTECTION_FIRE:1;IRON_LEGGINGS:0:1:1:PROTECTION_FIRE:1;IRON_HELMET:0:1:1:PROTECTION_FIRE:1;DIAMOND_CHESTPLATE:0:1:0.5:PROTECTION_FIRE:1;DIAMOND_LEGGINGS:0:1:0.5:PROTECTION_FIRE:1;DIAMOND_HELMET:0:1:0.5:PROTECTION_FIRE:1;IRON_CHESTPLATE:0:1:2:PROTECTION_PROJECTILE:1;IRON_LEGGINGS:0:1:1:PROTECTION_PROJECTILE:1;IRON_HELMET:0:1:1.5:PROTECTION_PROJECTILE:1;IRON_BOOTS:0:1:0.5:PROTECTION_PROJECTILE:1;DIAMOND_CHESTPLATE:0:1:3:PROTECTION_PROJECTILE:1;DIAMOND_LEGGINGS:0:1:1:PROTECTION_PROJECTILE:1;DIAMOND_HELMET:0:1:1:PROTECTION_PROJECTILE:1;IRON_CHESTPLATE:0:1:1:THORNS:1;IRON_LEGGINGS:0:1:1:THORNS:1;IRON_HELMET:0:1:1:THORNS:1;DIAMOND_CHESTPLATE:0:1:2:THORNS:1;DIAMOND_LEGGINGS:0:1:2:THORNS:1;DIAMOND_HELMET:0:1:2:THORNS:1;IRON_CHESTPLATE:0:1:0.5:THORNS:2;IRON_LEGGINGS:0:1:0.5:THORNS:2;IRON_HELMET:0:1:0.5:THORNS:2;DIAMOND_CHESTPLATE:0:1:1:THORNS:2;DIAMOND_LEGGINGS:0:1:1:THORNS:2;DIAMOND_HELMET:0:1:1:THORNS:2;DIAMOND_CHESTPLATE:0:1:0.5:PROTECTION_ENVIRONMENTAL:4;IRON_BOOTS:0:1:4:PROTECTION_FALL:1;DIAMOND_BOOTS:0:1:5:PROTECTION_FALL:1'
  2: 'IRON_PICKAXE:0:1:10:DIG_SPEED:3;DIAMOND_PICKAXE:0:1:7.5:DIG_SPEED:3;IRON_PICKAXE:0:1:5:DIG_SPEED:5;DIAMOND_PICKAXE:0:1:2.5:DIG_SPEED:5;GRILLED_PORK:0:1:25;CARROT:0:10:25;GRILLED_PORK:0:5:25'
  3: 'STONE_SWORD:0:1:5;IRON_SWORD:0:1:5.5;DIAMOND_SWORD:0:1:2.5;FISHING_ROD:0:1:7;BOW:0:1:5;ARROW:0:10:20;FLINT_AND_STEEL:0:1:5;IRON_SWORD:0:1:2.5:KNOCKBACK:1;DIAMOND_SWORD:0:1:2.5:KNOCKBACK:1;IRON_SWORD:0:1:3:FIRE_ASPECT:1;DIAMOND_SWORD:0:1:1:FIRE_ASPECT:1;STONE_SWORD:0:1:10:DAMAGE_ALL:1;IRON_SWORD:0:1:5:DAMAGE_ALL:1;DIAMOND_SWORD:0:1:5:DAMAGE_ALL:1;IRON_SWORD:0:1:2:DAMAGE_ALL:2;DIAMOND_SWORD:0:1:1:DAMAGE_ALL:2;DIAMOND_SWORD:0:1:0.5:DAMAGE_ALL:4;BOW:0:1:5:ARROW_KNOCKBACK:1;BOW:0:1:2.5:ARROW_DAMAGE:1;BOW:0:1:2:ARROW_DAMAGE:2;BOW:0:1:2.5:ARROW_FIRE:1;BOW:0:1:5.5:ARROW_INFINITE:1'
  4: 'EGG:0:1:10;TNT:0:1:10;SPLASH_POTION:0:1:10:HEAL:80:3:255;SPLASH_POTION:0:1:10:POISON:100:3:255;LAVA_BUCKET:0:1:10;WATER_BUCKET:0:1:10;COMPASS:0:1:10;MONSTER_EGG:60:1:10;GOLDEN_APPLE:0:1:20'


# KNOCKBACK:1  ARROW_INFINITE:1   ARROW_KNOCKBACK:1    FIRE_ASPECT:1  PROTECTION_ENVIRONMENTAL:1  PROTECTION_ENVIRONMENTAL:2  PROTECTION_FIRE:1   PROTECTION_PROJECTILE:1   THORNS:2
